### ISSUE TITLE
Add link to GitHub page for wiki when clicking the `Edit this page` button

### ISSUE THREAD

**Issue by toadsworth-jr** [TeamFluXis/fluXis-web#3]
![image](https://github.com/TeamFluXis/fluXis-web/assets/75596775/ab2712d1-a463-4c17-a426-b82e80fb7ce4)
I mean, the website says the wiki isn't open source, but it's right there.
![image](https://github.com/TeamFluXis/fluXis-web/assets/75596775/5d712149-443c-469d-bc91-a6d3fec58076)

**Comment by flustix** [comment]
Fixed in [83b6d07](https://github.com/TeamFluXis/fluXis-web/commit/83b6d07fca64ccfa9151724eb3122176df5e9221)
